"""
chat.py  —  /chat/ask endpoint
Uses OpenAI Chat Completions API (gpt-4.1-mini by default).
Set the OPENAI_API_KEY environment variable on Render.
"""

import os
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from openai import OpenAI, OpenAIError

chat_router = APIRouter(prefix="/chat", tags=["chat"])

# ---------------------------------------------------------------------------
# System prompt: gives the model context about the Living Atlas project
# ---------------------------------------------------------------------------
SYSTEM_PROMPT = """You are the RWC Living Atlas Helper, an AI assistant for the
Regional Water Center (RWC) Living Atlas web application — an interactive map
that showcases environmental datasets, GIS layers, and research resources for
the Pacific Northwest (Idaho, Oregon, and Washington).

Your role is to help users:
- Understand what data layers and datasets are available on the map
- Navigate features of the Living Atlas (search, filters, card system, custom layers, basemap switching, etc.)
- Answer questions about the environmental topics covered (water resources, land use, ecology, etc.)
- Explain how to use ArcGIS-linked layers and other tools in the app

Be concise, friendly, and factual. If you are unsure of something, say so rather
than making up information. Do not answer questions unrelated to the Living Atlas
or environmental/GIS topics.

⚠️ Note: This feature is currently under development. Answers are generated by an
AI model and may not always be accurate. Always verify critical information with
the data source directly.
"""

# ---------------------------------------------------------------------------
# Request / response schemas
# ---------------------------------------------------------------------------
class ChatRequest(BaseModel):
    question: str

class ChatResponse(BaseModel):
    answer: str

# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------
@chat_router.post("/ask", response_model=ChatResponse)
def ask(payload: ChatRequest):
    question = payload.question.strip()
    if not question:
        raise HTTPException(status_code=400, detail="Question must not be empty.")

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise HTTPException(
            status_code=503,
            detail="Chatbot is not configured (missing OPENAI_API_KEY). Please contact the administrator."
        )

    client = OpenAI(api_key=api_key)

    try:
        response = client.chat.completions.create(
            model=os.environ.get("OPENAI_MODEL", "gpt-4.1-mini"),
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": question},
            ],
            max_tokens=600,
            temperature=0.4,
        )
        answer = response.choices[0].message.content.strip()
        return ChatResponse(answer=answer)

    except OpenAIError as e:
        raise HTTPException(status_code=502, detail=f"AI service error: {str(e)}")
